README.md
I've updated all scripts (except those using the Events API or PDJS) to use v2 of the REST API
=> Updated to v2 of the PagerDuty API

mass_update_incidents/mass_update_incidents.py
* changed `iter_all` to `list_all`
* left comments about when to use which parameters
* added try and except logic around for loop to see error messages in the event that an incident update action fails
=> Isabella dev

mass_update_incidents/mass_update_incidents.py
* BUG: acknowledge feature was broken
* FEAT: support for running inside a virtualenv
* FEAT: add simple print to follow incident updates
=> Mass update incidents fixes

rerole_users/rerole_users.py
Change to refer to advanced_permissions.
=> AE-954 - update to refer to advanced_permissions

user_deprovision/README.md, user_deprovision/user_deprovision.py
Updates:
- Now able to use CSV file of emails
- Corrected EP processing error
=> Added use of csv file, also ES bug fix 

import_users/README.md
Contains some common caveats and requests- along with navigating whitespace issues.
=> Updated the readme

update_user_emails/README.md
quick update to the docs for the script to give instructions on how to use it with a CSV file.
=> add CSV instructions to Update User Emails

mass_update_incidents/mass_update_incidents.py
Update the script to support EU accounts
Added the US API URL (which EU supports) + ID, instead of using the self-value, which is different for US and EU accounts. This allows the script to pass pdpyras validation checks for url
* Tests script in EU account
* Test script in US account
- [] There is documentation that needs to be updated upon merging these changes
=> Update PUT request to support EU accounts

get_info_on_all_users/contact_methods.py
remove link to external repo
*
=> Remove link to external repo

schedule_layer_reorganizer/schedule_layer_reorganizer.py
Add python3 shebang line to allow execution
=> add shebang to schedule_layer_reorganizer

mass_update_incidents/README.md
https://pagerduty.atlassian.net/jira/software/c/projects/T2D2/boards/662?modal=detail&selectedIssue=T2D2-41
Updated the readme to include the script arguments and examples to showcase some of the use cases.
=> added script arguments and examples on how to run the script.

mass_update_incidents/mass_update_incidents.py
**Link back to Jira ticket: https://pagerduty.atlassian.net/browse/INCIDENTS-129**
Product limit work to protect our systems from excessive requests.
*
=> INCIDENTS-129 Add a delay in-between requests

update_user_emails/update_user_emails.py
Updated to support the EU pd accounts
=> updated to support EU accounts

migrate_webhooks_to_v3/README.md, migrate_webhooks_to_v3/migrate_webhooks_to_v3.py
**Link back to Jira ticket:** https://pagerduty.atlassian.net/browse/T2D2-42
Part of public support script audit.
Reviewed the script for sensitive information, tested that it still works, noticed that custom headers are not copied (as they are redacted in response to initial GET requests), so mentioned that in logging and README. Also created README.
* Review README
* Create a few v1/v2 webhooks on your sandbox account (including one with custom headers) and run the scrip to see them migrate to v3.
=> Add a warning for webhooks with custom headers T2D2-42

adding_tags/README.md, adding_tags/add_user_tags.rb
https://pagerduty.atlassian.net/browse/T2D2-117
Script to add tags on users. The script will find an existing user and will add defined tags from the CSV. 
A CSV with the following column is needed
email,tags
=> adding tags to users

migrate_webhooks_to_v3/README.md, migrate_webhooks_to_v3/migrate_webhooks_to_v3.py
Remove default behavior to migrate both v1 and v2 and update readme to add usage documentation.
=> Migrate webhooks update

update_user_emails/update_user_emails.py
- Sorted imports using isort
- Applied auto-formatter with black
No code behavior change. Formatter guarantees that no code functionality changes.
* NA - just applied formatting changes
NA
=> chore: sorted imports and ran auto-formatter

maintenance_windows_bulk_operations/README.md
just an edit to the README, making the filenames correct
=> tiny README edit

custom_field/README.md
Also added a collapsed example with raw csv syntax for reference.
Docs style improvement
* n/a (no code impact)
=> docs(style): improved markdown presentation of csv data

mass_update_incidents/mass_update_incidents.py
Incident Filtering is broken, currently being ignored by the API. This pull request adds a fix for that.
If the -i option is used, the included ids will be used as the incident list and the full incident list from the API will not be queried. Otherwise, the regular approach (querying the API) will be taken.
Please note that this fix doesn't include support for using incident numbers. The [update an incident](https://developer.pagerduty.com/api-reference/8a0e1aa2ec666-update-an-incident) endpoint requires incident ID in the URL and doesn't support incident number.
=> add incident filtering

user_deprovision/requirements.txt, user_deprovision/user_deprovision.py
Updated import module and class names required to move from pdpyras to pagerduty python library
Updated requirements.txt
=> [T2D2-338] Migrated user_deprovision.py script from pdpyras to python-pagerduty

update_user_emails/requirements.txt, update_user_emails/update_user_emails.py
Migrated from pdpyras to python-pagerduty
=> [T2D2-338] Migrated from pdpyras to python-pagerduty

rerole_users/requirements.txt, rerole_users/rerole_users.py, rerole_users/test.py
[https://pagerduty.atlassian.net/browse/T2D2-338]
Migrate rerole_users.py and test.py from pdpyras to pagerduty.py
=> T2D2-338 Migrate rerole_users.py from pdpyras to pagerduty.py

overrides_bulk_operations/get_overrides.py, overrides_bulk_operations/mass_delete_overrides.py, overrides_bulk_operations/requirements.txt, overrides_bulk_operations/vacation_overrides.py
Migrate overrides_bulk_operations from pdpyras to pagerduty.py
=> T2D2-338 Migrate overrides_bulk_operations from pdpyras to pagerduty.py

notifications_team_report/notifications_team_report.py, notifications_team_report/requirements.txt
Migrate notifications_team_report.py from pypyras to pagerduty.py
=> T2D2-338 Migrate notifications_team_report from pypyras to pagerduty.py

mass_update_incidents/mass_update_incidents.py, mass_update_incidents/requirements.txt
Migrate mass_update_incidents from pdpyras to pagerduty.py
=> T2D2-338 Migrate mass_update_incidents from pdpyras to pagerduty.py

export_routing_keys/export_routing_keys.py, export_routing_keys/requirements.txt
Migrate export_routing_keys from pdpyras to pagerduty.py
=> T2D2-338 Migrate export_routing_keys from pdpyras to pagerduty.py
