PagerDuty/public-support-scripts

import_users/import_users.rb

It does this by skipping the call to `add_contact_method` whenever phone number or country code are blank.

Fixed issue: user import loop skipping teams if phone fields are empty

---

import_users/import_users.rb

When Support receives user import csv's from Success, they're not always formatting correctly for the API. I added `.downcase` and `.strip` in case we get "Admin " instead of "admin".
I have tested this one case ("Admin ") and it worked.

Import user add strip and downcase

---

update_user_emails/update_user_emails.py

* Includes contact methods now by default
* Applies replacement logic to contact methods independent of the login email, which allows fixing stray contact methods that may still be invalid (even if the login email is fine), unless doing so for a CSV-based find and replace
* Empty replacement pattern strings now supported (they were triggering a "hey you didn't give me enough info" error)
* Add `fix_emails` asset tag since it can be used for this task now
* Eliminated unnecessary calls to update if there's no change; this vastly improves performance.

Fix a few bugs and improve option logic (in the user email update script)

---

.gitignore
rerole_users/rerole_users.py

The script is unclear about stating you need to specify two backup files. It is a better practice to always create backups with destructive actions. Now the script will use a default backup file if you do not specify one.

rerole_users.py: automatically create backup file

---

pull_request_template.md

**Link back to Jira ticket:** https://pagerduty.atlassian.net/browse/DOGE-325
This adds a default template to populate these fields whenever someone opens a pull request on this repo. This template is used for _this_ pull request.
Creating the pull request template within the repo using markdown - more information on this here: https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository
* Changes can be tested by opening a PR once the template is merged and seeing the template auto-populate.
Links to any documentation to be updated: N/A

[DOGE-325] Added PR template

---

.gitignore
import_users/README.md
import_users/import_users.rb

**Link back to Jira ticket:** [DOGE-326](https://pagerduty.atlassian.net/browse/DOGE-326)
Currently if there are errors on running the import user script they get buried in a sea of output on the terminal. This change will output all the errors to a log file. 
Create a log file on script start. Every time there is an error, push the https status, the response body, and the payload to the log file. 
* Run the script with bad data, see the errors in the log file but the good rows of the CSV still get users created for them .
I also update the readme for other reasons, no documentation changes needed for this update.

DOGE-326: Explicitly list errors at the end of the import user script

---

.gitignore
user_deprovision/README.md
user_deprovision/user_deprovision.py

**Link back to Jira ticket:** [DOGE-337](https://pagerduty.atlassian.net/browse/DOGE-337)
This pull request makes several changes to the user deprovision script. 
* PEP8 formatting
* Removes some unused and faulty logic
* Saves resource intensive API calls for future use
* No longer resolves incidents when deleting a user if there are additional responders besides the user being deleted. 
The original logic of the script retrieved all schedules, all users on each schedule, all teams, and all users on each team every time it went to delete a single user. If the script is to process a small amount of users on a small account, that would work okay. On a larger account this number of API calls quickly turns into a problem.
So instead of making those redundant API calls, we instantiate a …

DOGE-337: User Deprovision Update

---

import_users/import_users.rb

**Link back to Jira ticket:** https://pagerduty.atlassian.net/browse/DOGE-387
This Ruby script performs bulk import of users into PagerDuty account by communicating with our REST API. Previous version of the script logged errors in a log file created for each requester user email in the same folder as the script, while informational messages were output to the terminal. This pull request attempts to add verbosity to the log file for better tracking/understanding of the errors.
Logic of the script is split up between two classes: PagerDutyAgent defines methods for communicating with REST API and catches any errors returned from these requests, while CSVImporter reads provided csv file and passes the data for user creation into PagerDutyAgent's methods. Previous version of the script only …

Add info-level logging to bulk user import script

---

get_info_on_all_users/get_users_by_role.py

This script will take a comma separated list of roles as a command line argument and fetches all the users in an account that match one of roles provided in the list. Roles will be fetched in the order that they are provided in the command line argument. Running with -v flag will show which role is being retrieved and then list the members who match it. After retrieving all the members for a given role, a tally will be shown for how many users have that role. The script also creates a csv with names in the first column and users in the second. At the bottom of the CSV the totals for each role type are listed.  
`python get_users_by_role.py -k API-KEY-HERE -r COMMA-SEPARATED-ROLES-LIST`
acceptable values for roles: admin,read_only_user,read_only_limited_user,user,limited_user,observer,restr …

Isabella dev

---

import_users/import_users.rb

In its current state, the import users script will ignore new teams by default. When doing bulk uploads, customers often want to and expect the ability to simultaneously be able to create new teams to add their new users to. Doing this, however, requires running the script with a -t flag. I think it makes more sense to create new teams from the csv by default, as customers are unlikely to callout that they're also adding new teams, and if a tse is new or hasn't run the script in a while, they'll likely forget or not know to ask. I imagine the reason for disabling new team creation by default was to safeguard against inadvertently creating new teams that are actually just typos of existing teams. I think the default assumption should be that customers are giving us the correct information.

made creating new teams the default setting

---

import_users/README.md
import_users/import_users.rb

Don't have a jira ticket for this more of a proactive work
Last week had a real use case where a user wanted to update/create new users and add them to a team and set team roles. 
The new changes have the ability to add team roles for the given team(s) in the csv. 
If no team roles are supplied in the csv the default team role as responder will be added (this is what was happening in the first instance). 
If only 3 teams are supplied and there are 2 team roles, the third one will be a responder (default) and so on.
If only one team role is supplied for 1 or more teams, all the teams will be set as the defined role. 
* create a csv file with 1 team and 1 team_role
* create a csv file with 2 teams and 2 team_roles
* create a csv file with 3 teams and 3 …

Add team roles

---

import_users/README.md

removed the owner example as the account owner can not be created via the API. 
*

removed owner from docs as owner can not be created via API

---

mass_update_incidents/mass_update_incidents.py

https://pagerduty.atlassian.net/browse/ORCA-2344
https://pagerduty.slack.com/archives/CFMEAAR39/p1626366217205500?thread_ts=1626365505.205300&cid=CFMEAAR39
When running the mass resolve script, it skips all incidents that are in a suppressed state. Adding this param handles these use cases.
Un-comment line 17 'with_suppressed' to include suppressed incidents when querying incidents.
* Create and incident a Triggered suppressed stated 
* Run the script; this incident will be skipped 
* uncomment the line this incident will now be  included  

add param to handle suppressed incidents

---

import_users/README.md
import_users/import_users.rb

This PR improves a suboptimality whereby if a user being imported already existed (with the given email) AND country code and phone number provided matched an existing contact method (or are otherwise invalid), the user would not be added to the desired teams.  
For the case of existing users, the phone number/country code is apt to throw an error before that user can be added to teams, so I just switched the order such that it adds the user to any designated teams (a very un-error-prone operation) before it attempts to add a phone number contact method.
* Try importing a user with a new team name, a bogus country code and phone number, and an email that matches an existing user;  the existing user should be added to the new team.
Links to any documentation …

allow adding existing user to teams regardless of phone number

---

import_users/import_users.rb

Adds checks for presence of commas in title property of each user in the provided csv
**Link back to Jira ticket:** NA
This PR accounts for the cases where an unnoticed comma may be present in the user's title. This will result in an incorrect processing of the particular record of the input file, as the title column in that case will be treated by the script as two columns, with the second one corresponding to the country code.  This will also shift all the subsequent columns, resulting in data loss and / or misconfiguration.
The PR uses `to_a` method of the Struct class in order to extract and check the 5th parameter for each CSV record. If it is a null, a space or a numeric string, the script proceeds with user import. Otherwise, the script will offer an option to abort or proceed with …

Adds checks for presence of commas in title property

---

schedule_layer_reorganizer/README.md
schedule_layer_reorganizer/requirements.txt
schedule_layer_reorganizer/schedule_layer_reorganizer.py

A script that can be used as a tool to more easily update schedules that have multiple layers on them. Currently, a GET request and a POST or PUT request for a schedule will have schedule layers in opposite order. This tool GETs a schedule and saves it to a file with the layers reversed so that the payload can easily be sent as a PUT or POST request without reversing the order of the schedule layers.
GET a schedule
Iterate through the schedule layers of the schedule and save to a list in reversed order
Replace the existing list with the reversed list in the schedule object
Write the JSON to a file
* Run the GET on a multi-layered schedule
* Copy the response and send it as a PUT request
* No changes to the schedule should occur 
- [] There is documentation that needs to be updated upon …

Add schedule layer reorganizer script

---

get_info_on_all_users/contact_methods.py

**Link back to Jira ticket:** [T2D2-31](https://pagerduty.atlassian.net/jira/software/c/projects/T2D2/issues/T2D2-31)
Changes were made to pdpyras three months ago that switched several logs from debug level to warning level. Because of that, when running the script to get all contact methods for an account, a warning is printed after every single user’s name. This fixes that by suppressing warnings.
Disable logging for WARNING level and below.
* Run contact_methods.py on Master vs this branch to see the difference

[T2D2-31] Suppress pagination warnings in contact_methods.py

---

mass_update_incidents/mass_update_incidents.py

https://pagerduty.atlassian.net/browse/INCIDENTS-129
this PR just adds an additional argument to the request header
`"X-SOURCE-SCRIPT": "pupblic-support-scripts/mass_update_incidents"`
A manual sleep/rate limit is not necessary since the pdpyras library has protection baked in.
https://pagerduty.github.io/pdpyras/#cooldown
*

INCIDENTS-129 add argument to request header

---

notifications_team_report/README.md
notifications_team_report/notifications_team_report.py

**Link back to Jira ticket:** [T2D2-43](https://pagerduty.atlassian.net/browse/T2D2-43)
This is a cleanup PR as part of T2D2-36 work. 
The main changes here are as follows:
- Adds a README file for the folder
- Switches `-t/--token` to `-k/--api-key` to match other scripts in this repo
- Makes the API key required in argparse instead of erroring at the pdpyras level
- Changes verbosity behavior from needing to enter `-v` five times to get debug level, to just either verbose or not
- Moves progress reporting to the verbose/debug logging
* Pull down branch and run `./notifications_team_report.py` with no args: it will now error in argparse instead of pdpyras
* Run with valid key: it will run at INFO level logging with no progress reports
* Run with valid key and `-v` flag: It will run with …

[T2D2-43] Clean up notifications_team_report folder

---

import_users/import_users.rb

https://pagerduty.atlassian.net/browse/T2D2-132
When making an initial connection and if the API key is incorrect, the error message returned was utterly misleading.
Added a check which will display an error message "401 Unauthorised" if an incorrect key is entered.

verifying if API key exists or not

---

custom_field/README-DEV.md

"<your-domain>" was not rendering due to being treated as an html tag.  Made some minor text changes while I was in.
Minor README-DEV change
n/a
n/a
n/a

docs(dev): html escape display fix + minor changes

---

get_info_on_all_users/contact_methods.py

The `users/{id}/contact_methods` endpoint was being requested via the "iter_all" method, however, there is no expected "more" field in the contact_methods response and pagination does not exist and is not required for that endpoint. This results in a warning message upon running the script.
Change iter_all method to the rget method for the call to the `users/{id}/contact_methods` endpoint.
* test script with iter_all and rget methods to confirm
* also confirm that there is no case where iter_all needs to be used because the `users/{id}/contact_methods` endpoint does not support pagination and users can only have a maximum of [10 contact methods](https://support.pagerduty.com/docs/user-profile#add-a-phone-sms-or-email-contact-method) at this time.
- N/A

change iter_all to rget 

---

get_info_on_all_users/get_users_by_role.py

Previously the append flag was true reuslting in re-appending of CSV header and new content if command was re-run.
[T2D2-306](https://pagerduty.atlassian.net/jira/software/c/projects/T2D2/boards/662?quickFilter=3273&selectedIssue=T2D2-306)
script would append to existing files, including header - breaking at best syntax and possibly only semantics
[Bug report](https://github.com/PagerDuty/public-support-scripts/issues/115)
simply made writer mode a passed variable, with an append default
* manual testing
- no changes needed
[T2D2-306]: https://pagerduty.atlassian.net/browse/T2D2-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: script no longer appends on new run

---

mass_update_incidents/README.md
mass_update_incidents/mass_update_incidents.py

**Link back to Jira ticket:** https://pagerduty.atlassian.net/browse/INCIDENTS-2494
Updates the bulk-update script to take alert counts into consideration when handling incident resolution. This ensures that rate limits are not hit when bulk-resolving. 
* Updates the script from using the single-update endpoint to instead using the bulk-update endpoint, which should be more efficient
* Fetches the incident object, even when a list of incident ids is passed in, if we're doing a resolve action
* Uses the alert count of the incidents to manage waiting between batches of requests, to avoid hitting rate limits
* Run the script, with various flags enabled to verify the behaviour and logging

Updates the bulk-update script to take alert counts into consideration when handling incident resolution. 
